CREATE TABLE `exercicim13`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `job` ENUM('ALL', 'MANAGER', 'SENIOR_PROGRAMMER', 'MEDIUM_PROGRAMMER', 'JUNIOR_PROGRAMMER', 'ADMINISTRATIVE') NOT NULL,
  `salary` DOUBLE NOT NULL,
  PRIMARY KEY (`id`));

INSERT INTO employees VALUES (DEFAULT, 'Anna Grau', 'MANAGER', 100000);
INSERT INTO employees VALUES (DEFAULT, 'Pere Pou', 'SENIOR_PROGRAMMER', 70000);
INSERT INTO employees VALUES (DEFAULT, 'Laura Abat', 'SENIOR_PROGRAMMER', 70000);
INSERT INTO employees VALUES (DEFAULT, 'Joan Lluna', 'JUNIOR_PROGRAMMER', 30000);
INSERT INTO employees VALUES (DEFAULT, 'Berta Sol', 'JUNIOR_PROGRAMMER', 30000);
INSERT INTO employees VALUES (DEFAULT, 'Jordi Pont', 'ADMINISTRATIVE', 25000);